#!/bin/bash
#This bash script will delete all files under a directory based
#on how old those files are.  Empty directories will be deleted as well.

#Sean Begley
#begleysm@gmail.com
#https://steamforge.net/wiki
#https://github.com/begleysm/ipcam-ftp-tools
#2019-07-17

#first parameter ($1) = path to directory to cleanup
#second parameter ($2) = number of days of content to keep
#example usage = ./del-older-than /path/to/parent/directory/ 14

age=$(($2-1));
find $1 -mindepth 1 -mtime +$age -type f -delete
find $1 -mindepth 1 -type d -empty -delete
